"""TOCS semantic evidence contract layer.

Provider-neutral types for the CodeGraph/DocGraph query interface defined in
``TOCS_CodeGraph_DocGraph_Offline_Evidence_Enhancement_Requirements_v0.1.md``.
"""

from .alias import CrossGraphAliasBuilder, read_cross_graph_aliases
from .extractor import SemanticBuildResult, SemanticLayerBuilder
from .query import SemanticGraphQueryHandler
from .types import (
    AliasKind,
    AuthorityScope,
    CapabilityName,
    CapabilitySupport,
    CoverageGapReason,
    DatasetRevision,
    EntityKind,
    EvidenceCoverageGap,
    EvidenceKind,
    EvidenceRef,
    EvidenceStrength,
    ExtractionMethod,
    GraphCapabilityManifest,
    GraphDatasetManifest,
    GraphKind,
    Modality,
    QueryDiagnostics,
    QueryLimits,
    QueryScenario,
    QueryStatus,
    QuerySubject,
    RelationKind,
    RevisionMappingStatus,
    RevisionScheme,
    SemanticEntity,
    SemanticEntityAlias,
    SemanticGraphQuery,
    SemanticGraphQueryResult,
    SemanticRelation,
    SourceLocator,
)

__all__ = [
    "AliasKind",
    "AuthorityScope",
    "CapabilityName",
    "CapabilitySupport",
    "CoverageGapReason",
    "CrossGraphAliasBuilder",
    "DatasetRevision",
    "EntityKind",
    "EvidenceCoverageGap",
    "EvidenceKind",
    "EvidenceRef",
    "EvidenceStrength",
    "ExtractionMethod",
    "GraphCapabilityManifest",
    "GraphDatasetManifest",
    "GraphKind",
    "Modality",
    "QueryDiagnostics",
    "QueryLimits",
    "QueryScenario",
    "QueryStatus",
    "QuerySubject",
    "RelationKind",
    "RevisionMappingStatus",
    "RevisionScheme",
    "SemanticBuildResult",
    "SemanticEntity",
    "SemanticEntityAlias",
    "SemanticGraphQuery",
    "SemanticGraphQueryHandler",
    "SemanticGraphQueryResult",
    "SemanticLayerBuilder",
    "SemanticRelation",
    "SourceLocator",
    "read_cross_graph_aliases",
]
